<script lang="ts" context="module">
	export const langNames: Record<string, string> = {
		acw: 'Hijazi Arabic',
		akk: 'Akkadian',
		amh: 'Amharic',
		ara: 'Arabic',
		arc: 'Official Aramaic (700-300 BCE)',
		atz: 'Arta',
		ave: 'Avestan',
		aze: 'Azerbaijani',
		bak: 'Bashkir',
		bam: 'Bambara',
		ben: 'Bengali',
		bod: 'Tibetan',
		bqi: 'Bakhtiari',
		bul: 'Bulgarian',
		chg: 'Chagatai',
		chu: 'Old Slavonic',
		cop: 'Coptic',
		dan: 'Danish',
		dar: 'Dargwa',
		deu: 'German',
		efi: 'Efik',
		egy: 'Egyptian (Ancient)',
		ell: 'Modern Greek (1453-)',
		elx: 'Elamite',
		emk: 'Eastern Maninkakan',
		emy: 'Epigraphic Mayan',
		eng: 'English',
		erk: 'South Efate',
		fas: 'Persian',
		fra: 'French',
		ful: 'Fulah',
		gez: 'Geez',
		gml: 'Middle Low German',
		got: 'Gothic',
		grc: 'Ancient Greek (to 1453)',
		guj: 'Gujarati',
		hac: 'Gurani',
		hau: 'Hausa',
		heb: 'Hebrew',
		hin: 'Hindi',
		hit: 'Hittite',
		hun: 'Hungarian',
		hye: 'Armenian',
		imy: 'Milyan',
		ind: 'Indonesian',
		inm: 'Minaean',
		ita: 'Italian',
		jav: 'Javanese',
		jpn: 'Japanese',
		jpr: 'Judeo-Persian',
		jrb: 'Judeo-Arabic',
		kac: 'Kachin',
		kan: 'Kannada',
		kas: 'Kashmiri',
		kat: 'Georgian',
		kbl: 'Kanembu',
		kgv: 'Karas',
		khm: 'Khmer',
		kur: 'Kurdish',
		lat: 'Latin',
		lav: 'Latvian',
		lit: 'Lithuanian',
		lzz: 'Laz',
		mal: 'Malayalam',
		mar: 'Marathi',
		mku: 'Konyanka Maninka',
		mlt: 'Maltese',
		mon: 'Mongolian',
		mzn: 'Mazanderani',
		nep: 'Nepali (macrolanguage)',
		nld: 'Flemish',
		nrp: 'North Picene',
		ofs: 'Old Frisian',
		oge: 'Old Georgian',
		orv: 'Old Russian',
		osc: 'Oscan',
		oss: 'Ossetic',
		osx: 'Old Saxon',
		ota: 'Ottoman Turkish (1500-1928)',
		pal: 'Pahlavi',
		pli: 'Pali',
		por: 'Portuguese',
		que: 'Quechua',
		raj: 'Rajasthani',
		ron: 'Romanian',
		rus: 'Russian',
		san: 'Sanskrit',
		snd: 'Sindhi',
		snk: 'Soninke',
		sog: 'Sogdian',
		spa: 'Spanish',
		sqi: 'Albanian',
		sux: 'Sumerian',
		sva: 'Svan',
		swe: 'Swedish',
		syr: 'Syriac',
		tab: 'Tabassaran',
		tam: 'Tamil',
		tat: 'Tatar',
		tdn: 'Tondano',
		tel: 'Telugu',
		tgk: 'Tajik',
		tio: 'Teop',
		tir: 'Tigrinya',
		tks: 'Takestani',
		tru: 'Turoyo',
		tuh: 'Taulil',
		tuk: 'Turkmen',
		tur: 'Turkish',
		udi: 'Udi',
		uga: 'Ugaritic',
		ukr: 'Ukrainian',
		und: 'Undetermined',
		urd: 'Urdu',
		uzb: 'Uzbek',
		vra: "Vera'a",
		wlm: 'Middle Welsh',
		xbc: 'Bactrian',
		xbm: 'Middle Breton',
		xcr: 'Carian',
		xeb: 'Eblan',
		xlc: 'Lycian',
		xld: 'Lydian',
		xlp: 'Lepontic',
		xmn: 'Manichaean Middle Persian',
		xna: 'Ancient North Arabian',
		xpg: 'Phrygian',
		xpr: 'Parthian',
		xqt: 'Qatabanian',
		xsa: 'Sabaean',
		xum: 'Umbrian',
		xur: 'Urartian',
		yid: 'Yiddish',
		yor: 'Yoruba',
		zho: 'Chinese',
		zum: 'Kumzari'
	};
</script>
