name: Monthly Release

on:
  schedule:
    - cron: '0 0 1 * *'  
  workflow_dispatch:  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Get latest version tag
        id: get_latest_tag
        run: |          
          latest_tag=$(git tag --sort=-v:refname | grep '^v' | head -n 1)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV  

      - name: Compute next minor version
        id: compute_version
        env:
          tag: ${{ env.tag }} 
        run: |
          tag="$tag"
          tag="${tag#v}"  # Strip the 'v' from the beginning
          IFS='.' read -r major minor patch <<< "$tag"
          minor=$((minor + 1))
          new_tag="v$major.$minor.0"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

     
        
