name: Monthly Release

on:
  schedule:
    - cron: '0 0 1 * *'  
  workflow_dispatch:  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest version tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | grep '^v' | head -n 1)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV  # Corrected to set the output to GITHUB_ENV

      - name: Compute next minor version
        id: compute_version
        run: |
          # Extract major, minor, patch from latest tag
          IFS='.' read -r major minor patch <<< "${{ env.tag#v }}"  # Using env variable for latest tag
          minor=$((minor + 1))  # Increment minor version
          new_tag="v$major.$minor.0"  # Set patch version to 0
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV  # Set output to GITHUB_ENV

      - name: Generate release notes
        id: generate_notes
        run: |
          previous_tag="${{ env.tag }}"
          new_tag="${{ env.new_tag }}"
          notes_url="https://github.com/${{ github.repository }}/compare/${previous_tag}...${new_tag}"
          echo "Release notes: Comparison between $previous_tag and $new_tag"
          echo "release_notes=See changes: $notes_url" >> $GITHUB_ENV  # Set output to GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_tag }}  
          name: Release ${{ env.new_tag }}  
          body: ${{ env.release_notes }}  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
