name: Schema validation with Deno

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  validate:
    name: Validate project files

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Run tests
        run: deno test --allow-read TESTS/schema_tests.ts
